baseURL = 'https://www.mindthespines.com/'
languageCode = 'en-us'
title = 'Mind the Spines'
copyright = '2022 Devon Wolfkiel'

[menu]
  [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 1

  [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 3

  [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 2

[params]
  description = "A blog about books, ebooks, and personal libraries"
  author = "Devon Wolfkiel"

  # backgroundColor = ""
  # textColor = ""
  # accentColor = ""
  # navColor = ""
  # linkColor = ""
  # visitedLinkColor = ""

  # backgroundColorDarkMode = ""
  # textColorDarkMode = ""
  # accentColorDarkMode = ""
  # navColorDarkMode = ""
  # linkColorDarkMode = ""
  # visitedLinkColorDarkMode = ""

  # font = ""
  